# ------------------------------------------------------------
#
# ZabbixサーバーとPostgresqlを同一サーバー内で構築するPlaybook
#
# ------------------------------------------------------------

- name: Zabbix-Serverの構築
  hosts: zabbix_servers    # ansibleの実行先サーバーのプライベートIPアドレス
  gather_facts: no
  become: true    # root権限で実行

  # ------------------------------------------------------------
  #
  #  環境変数
  #
  # ------------------------------------------------------------

  vars:
    timezone: Asia/Tokyo    # 設定するTimezoneを指定
    pg_version: 15          # postgresqlのバージョンを指定
    pg_data_dir: /var/lib/pgsql/data    # postgresqlのデータ保存ディレクトリを指定
    zabbix_schema_file: /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz    # Zabbixの初期スキーマファイルを指定
    zabbix_server_conf_file: /etc/zabbix/zabbix_server.conf                       # Zabbixサーバーの設定ファイル
    zabbix_agent_conf_file: /etc/zabbix/zabbix_agent2.conf                        # Zabbixエージェントの設定ファイル
    zabbix_server_host: 172.31.6.65     # Postgresqlが接続を許可するZabbixサーバーのプライベートIPアドレス
    zabbix_server_host_mask: 32         # Postgresqlが接続を許可するZabbixサーバーのサブネットマスク
    #zabbix_agent_host:
    db_host: 172.31.6.65                  # Postgresqlが構築されているサーバーのプライベートIPアドレス
    db_name: zabbix                       # Postgresqlのデータベースの名前
    db_user: zabbix                       # Postgresqlのユーザー名
    db_pass: zabbix                       # Postgresqlのユーザーに対するパスワード
    zabbix_agent_hostname: Zabbix-Agent   # Zabbixエージェントのホスト名
    zabbix_server_confs:
      - regexp: '^# DBHost=localhost'
        line: 'DBHost={{ db_host }}'
      - regexp: '^# DBName=zabbix'
        line: 'DBName={{ db_name }}'
      - regexp: '^# DBUser=zabbix'
        line: 'DBUser={{ db_user }}'
      - regexp: '^# DBPassword='
        line: 'DBPassword={{ db_pass }}'
    zabbix_agent_confs:
      - regexp: '^Server='
        line: 'Server={{ zabbix_server_host }}'
      - regexp: '^ServerActive='
        line: 'ServerActive={{ zabbix_server_host }}'
      - regexp: '^Hostname='
        line: 'Hostname={{ zabbix_agent_hostname }}'

  tasks:
  # ------------------------------------------------------------
  #
  # 1. システム設定
  #
  # ------------------------------------------------------------
  
    # パッケージの更新（dnf update）
    - name: Upgrade all packages
      dnf:                              # ansible.builtin.dnf
        name: "*"
        state: latest

    # timezone を Asia/Tokyo に変更（timezdatectl set-timezone Asia/Tokyo）
    - name: Change timezone
      timezone:                         # community.general.timezone
        name: "{{ timezone }}"

  # ------------------------------------------------------------
  #
  # 2.Postgresql設定
  #
  # ------------------------------------------------------------
      
    # postgresqlのインストール（dnf install postgresql15-server）
    - name: Install postgresql
      dnf:                              # ansible.builtin.dnf
        name: "postgresql{{ pg_version }}-server"
        # パッケージがインストールされている状態にする。すでに存在する場合は何もしない。
        state: present

    # python3-psycopg2のインストール（community.postgresqlモジュールをターゲットノードで実行するために必要）
    - name: Install python3-psycopg2
      dnf:                              # ansible.builtin.dnf
        name: python3-psycopg2
        state: present

    # postgresqlの初期化（postgresql-setup --initdb）
    - name: Initialization of postgresql
      command:                          # ansible.builtin.commmand
        cmd: postgresql-setup --initdb
        creates: "{{ pg_data_dir }}/PG_VERSION"  # 左記のファイルが存在する場合はこの初期化タスク自体スキップ

    # postgresqlの起動
    - name: Start postgresql
      systemd:                          # ansible.builtin.systemd_service
        name: postgresql.service
        state: started
        enabled: true

    # postgresql.confの接続設定
    - name: Edit postgresql.conf
      replace:                          # ansible.builtin.replace
        path: "{{ pg_data_dir }}/postgresql.conf"
        regexp: "^#listen_addresses = 'localhost'"
        replace: "listen_addresses = '*'"
        backup: true
      register: pg_conf_result

    # pg_hba.confのルール追加
    - name: Add rule to pg_hba.conf
      postgresql_pg_hba:                # community.postgresql.postgresql_pg_hba
        dest: "{{ pg_data_dir }}/pg_hba.conf"
        source: "{{ zabbix_server_host }}/{{ zabbix_server_host_mask }}"
        contype: host
        databases: "{{ db_name }}"
        users: "{{ db_user }}"
        method: scram-sha-256
        state: present
        backup: true
      register: pg_hba_result

    # postgresql.conf または pg_hba.conf が変更された場合のみ再起動
    - name: Restart postgresql if configs changed
      systemd:                          # ansible.builtin.systemd_service
        name: postgresql.service
        state: restarted
      when: pg_conf_result.changed or pg_hba_result.changed

    # Zabbix専用ユーザー作成
    - name: Create zabbix-user
      postgresql_user:                  # community.postgresql.postgresql_user
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        state: present
      become_user: postgres

    # Zabbix専用データベース作成
    - name: Create zabbix-db
      postgresql_db:                    # community.postgresql.postgresql_db
        name: "{{ db_name }}"
        owner: "{{ db_user }}"
        state: present
      become_user: postgres

  # ------------------------------------------------------------
  #
  # 3.Zabbix Server 設定
  #
  # ------------------------------------------------------------

    # Zabbix 7.0 リポジトリの追加
    - name: Add zabbix 7.0 repository
      dnf:                              # ansible.builtin.dnf
        name: "https://repo.zabbix.com/zabbix/7.0/amazonlinux/2023/x86_64/zabbix-release-latest-7.0.amzn2023.noarch.rpm"
        state: present
        disable_gpg_check: true

    # Zabbix パッケージインストール
    - name: Install zabbix packages
      dnf:                              # ansible.builtin.dnf
        name:
          - zabbix-server-pgsql         # Zabbixサーバーの本体
          - zabbix-web-pgsql            # Web管理画面の本体
          - zabbix-apache-conf          # Webサーバー用の設定ファイル
          - zabbix-sql-scripts          # 初期データベース作成用スクリプト
          - zabbix-web-japanese         # Web画面の日本語化パッケージ
          - zabbix-agent2               # 監視対象に入れるデータ収集プログラム
        state: present
        disable_gpg_check: true
    
    # Zabbix DBスキーマの投入
    - name: Include db schema
      postgresql_db:                    # community.postgresql.postgresql_db
        name: "{{ db_name }}"
        target: "{{ zabbix_schema_file }}"
        state: restore
        login_user: "{{ db_user }}"
        login_host: "{{ db_host }}"
      environment:
        PGPASSWORD: "{{ db_pass }}"

    # ZabbixサーバーがDBへ接続するための設定
    - name: configure zabbix-server to database
      lineinfile:                       # ansible.builtin.lineinfile
        path: "{{ zabbix_server_conf_file }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backup: true
      loop: "{{ zabbix_server_confs }}"

    # Zabbixサーバーの起動
    - name: Start zabbix-server
      systemd:                          # ansible.builtin.systemd_service
        name: zabbix-server
        state: started
        enabled: true

    # Zabbixエージェントの設定
    - name: Configure zabbix-agent
      lineinfile:                       # ansible.builtin.lineinfile
        path: "{{ zabbix_agent_conf_file }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backup: true
      loop: "{{ zabbix_agent_confs }}"

    # Zabbixエージェントの起動
    - name: Start zabbix-agent
      systemd:                          # ansible.builtin.systemd_service
        name: zabbix-agent2
        state: started
        enabled: true

    # Apacheの起動
    - name: Start httpd
      systemd:                          # ansible.builtin.systemd_service
        name: httpd
        state: started
        enabled: true

